development: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: movies_development
  pool: 5
  username: root
  password:

test:
  <<: *defaults
  database: movies_test

production:
  development